CREATE TABLE "teachers"
(
    "id"         bigint primary key,
    "first_name" text,
    "last_name"  text,
    "email"      text,
    "sex"        text,
    "school"     text
);

INSERT INTO "teachers"
VALUES (1, 'Dougie', 'McCluney', 'dmccluney0@nsw.gov.au', 'M', 'GP'),
       (2, 'Skip', 'Dunford', 'sdunford1@godaddy.com', 'M', 'GP'),
       (3, 'Will', 'Murrow', 'wmurrow2@prnewswire.com', 'M', 'GP'),
       (4, 'Laurens', 'Oldred', 'loldred3@unblog.fr', 'M', 'GP'),
       (5, 'Lev', 'Piscotti', 'lpiscotti4@hao123.com', 'M', 'MS'),
       (6, 'Herman', 'Ashbridge', 'hashbridge5@about.com', 'M', 'MS'),
       (7, 'Levin', 'Mattam', 'lmattam6@sohu.com', 'F', 'MS'),
       (8, 'Reinwald', 'Throssell', 'rthrossell7@china.com.cn', 'M', 'MS'),
       (9, 'Chrissy', 'Blackeby', 'cblackeby8@jiathis.com', 'M', 'MS'),
       (10, 'Borden', 'Urch', 'burch9@jugem.jp', 'M', 'MS'),
       (11, 'Jordon', 'Oldman', 'joldmana@artisteer.com', 'M', 'MS'),
       (12, 'Duncan', 'Blaxill', 'dblaxillb@apache.org', 'M', 'MS'),
       (13, 'Christopher', 'Collecott', 'ccollecottc@foxnews.com', 'F', 'MS'),
       (14, 'Claire', 'Tennison', 'ctennisond@storify.com', 'F', 'MS'),
       (15, 'Tobiah', 'Fozard', 'tfozarde@fda.gov', 'F', 'MS'),
       (16, 'Natal', 'Thredder', 'nthredderf@smh.com.au', 'M', 'MS'),
       (17, 'Maje', 'Kinkead', 'mkinkeadg@newsvine.com', 'M', 'MS'),
       (18, 'Logan', 'Blueman', 'lbluemanh@mysql.com', 'M', 'MS'),
       (19, 'Lionel', 'Elden', 'leldeni@free.fr', 'M', 'GP'),
       (20, 'Early', 'Shitliffe', 'eshitliffej@soup.io', 'M', 'GP'),
       (21, 'Vasili', 'Soloway', 'vsolowayk@yelp.com', 'M', 'GP'),
       (22, 'Briano', 'Youll', 'byoulll@nature.com', 'M', 'GP'),
       (23, 'Bearnard', 'Caseley', 'bcaseleym@quantcast.com', 'M', 'GP'),
       (24, 'Gaby', 'Surmon', 'gsurmonn@epa.gov', 'F', 'GP'),
       (25, 'Brocky', 'Burleigh', 'bburleigho@howstuffworks.com', 'F', 'GP'),
       (26, 'Charley', 'Rallings', 'crallingsp@51.la', 'F', 'GP'),
       (27, 'Job', 'Rosenblath', 'jrosenblathq@technorati.com', 'F', 'GP'),
       (28, 'Borg', 'Espinoza', 'bespinozar@sciencedaily.com', 'F', 'GP'),
       (29, 'Borg', 'Wickardt', 'bwickardts@thetimes.co.uk', 'F', 'GP'),
       (30, 'Constantino', 'Kingsland', 'ckingslandt@xrea.com', 'F', 'GP'),
       (31, 'Stanford', 'Benson', 'sbensonu@slate.com', 'F', 'GP'),
       (32, 'Edlin', 'Smidmor', 'esmidmorv@last.fm', 'F', 'GP'),
       (33, 'Stern', 'Muldoon', 'smuldoonw@diigo.com', 'M', 'GP'),
       (34, 'Herve', 'Wort', 'hwortx@aboutads.info', 'M', 'MS'),
       (35, 'Gib', 'Chaudron', 'gchaudrony@state.gov', 'M', 'MS'),
       (36, 'Gamaliel', 'Byart', 'gbyartz@google.com.br', 'M', 'MS'),
       (37, 'Forester', 'Coules', 'fcoules10@skype.com', 'M', 'MS'),
       (38, 'Huberto', 'Humblestone', 'hhumblestone11@bloomberg.com', 'M', 'MS'),
       (39, 'Justus', 'Mears', 'jmears12@tripadvisor.com', 'M', 'MS'),
       (40, 'Staffard', 'Halton', 'shalton13@zimbio.com', 'M', 'GP'),
       (41, 'Armand', 'Kelston', 'akelston14@forbes.com', 'M', 'GP'),
       (42, 'De witt', 'Brownsword', 'dbrownsword15@apple.com', 'M', 'GP'),
       (43, 'Cory', 'Bartrop', 'cbartrop16@goo.ne.jp', 'M', 'GP'),
       (44, 'Hilary', 'Cutford', 'hcutford17@usnews.com', 'F', 'GP'),
       (45, 'Valentijn', 'Cella', 'vcella18@macromedia.com', 'F', 'GP'),
       (46, 'Giacomo', 'Millhill', 'gmillhill19@smh.com.au', 'F', 'GP'),
       (47, 'Decca', 'Lippi', 'dlippi1a@icq.com', 'F', 'MS'),
       (48, 'Gannie', 'Overstall', 'goverstall1b@icq.com', 'F', 'GP'),
       (49, 'Emmett', 'Vanni', 'evanni1c@thetimes.co.uk', 'F', 'MS'),
       (50, 'Hartley', 'Lauritzen', 'hlauritzen1d@house.gov', 'F', 'GP'),
       (51, 'Manfred', 'Chellam', 'mchellam1e@cdc.gov', 'M', 'MS'),
       (52, 'Jerome', 'Wharrier', 'jwharrier1f@businessweek.com', 'M', 'GP'),
       (53, 'Fraze', 'Plumley', 'fplumley1g@cnn.com', 'M', 'MS'),
       (54, 'Merv', 'Frie', 'mfrie1h@reuters.com', 'M', 'GP'),
       (55, 'Wyndham', 'Americi', 'wamerici1i@jiathis.com', 'M', 'MS'),
       (56, 'Harrison', 'Mannock', 'hmannock1j@virginia.edu', 'M', 'GP'),
       (57, 'Clayborn', 'Tesche', 'ctesche1k@issuu.com', 'F', 'MS'),
       (58, 'Wildon', 'Mower', 'wmower1l@fastcompany.com', 'F', 'GP'),
       (59, 'Gilbert', 'MacGill', 'gmacgill1m@unblog.fr', 'F', 'MS'),
       (60, 'Tristam', 'Ivins', 'tivins1n@vinaora.com', 'F', 'GP'),
       (61, 'Carter', 'Blum', 'cblum1o@comcast.net', 'F', 'GP'),
       (62, 'Boigie', 'Ruoff', 'bruoff1p@aboutads.info', 'F', 'GP'),
       (63, 'David', 'Grishanov', 'dgrishanov1q@de.vu', 'F', 'GP'),
       (64, 'Brendon', 'Grubey', 'bgrubey1r@nhs.uk', 'M', 'GP'),
       (65, 'Trev', 'Ewers', 'tewers1s@uiuc.edu', 'M', 'GP'),
       (66, 'Robinson', 'Sprasen', 'rsprasen1t@mapquest.com', 'M', 'GP'),
       (67, 'Banky', 'MacTimpany', 'bmactimpany1u@forbes.com', 'M', 'MS'),
       (68, 'Moritz', 'Alexsandrev', 'malexsandrev1v@1und1.de', 'M', 'GP'),
       (69, 'Arlan', 'Lalevee', 'alalevee1w@hatena.ne.jp', 'M', 'GP'),
       (70, 'Wolfie', 'Cud', 'wcud1x@github.com', 'M', 'GP'),
       (71, 'Creigh', 'Fardoe', 'cfardoe1y@netlog.com', 'M', 'GP'),
       (72, 'Cole', 'Rehor', 'crehor1z@usgs.gov', 'M', 'GP'),
       (73, 'Pyotr', 'Feather', 'pfeather20@google.it', 'M', 'MS'),
       (74, 'Bennie', 'Durtnal', 'bdurtnal21@moonfruit.com', 'M', 'MS'),
       (75, 'Hyatt', 'Gumary', 'hgumary22@plala.or.jp', 'M', 'MS'),
       (76, 'Prentice', 'Shepstone', 'pshepstone23@newyorker.com', 'F', 'MS'),
       (77, 'Warner', 'Lesor', 'wlesor24@feedburner.com', 'F', 'MS'),
       (78, 'Chicky', 'Kembry', 'ckembry25@kickstarter.com', 'F', 'MS'),
       (79, 'Regen', 'Zamora', 'rzamora26@eventbrite.com', 'F', 'MS'),
       (80, 'Timothy', 'Leates', 'tleates27@drupal.org', 'F', 'MS'),
       (81, 'Anson', 'Walczynski', 'awalczynski28@scribd.com', 'F', 'MS'),
       (82, 'Sayer', 'Kyncl', 'skyncl29@paypal.com', 'F', 'MS'),
       (83, 'Ignazio', 'Yeoman', 'iyeoman2a@cornell.edu', 'F', 'GP'),
       (84, 'Adolph', 'Michell', 'amichell2b@google.cn', 'F', 'GP'),
       (85, 'Giraud', 'Chewter', 'gchewter2c@1und1.de', 'F', 'GP'),
       (86, 'Bobby', 'Spellworth', 'bspellworth2d@jalbum.net', 'F', 'GP'),
       (87, 'Marlo', 'Rispen', 'mrispen2e@mayoclinic.com', 'F', 'GP'),
       (88, 'Reinaldo', 'Morriarty', 'rmorriarty2f@about.me', 'F', 'MS'),
       (89, 'Glynn', 'Lidgey', 'glidgey2g@elegantthemes.com', 'M', 'MS'),
       (90, 'Eadmund', 'Preskett', 'epreskett2h@buzzfeed.com', 'M', 'MS'),
       (91, 'Nikolai', 'Sedgemond', 'nsedgemond2i@cmu.edu', 'F', 'MS'),
       (92, 'Gordon', 'Denerley', 'gdenerley2j@nydailynews.com', 'F', 'MS'),
       (93, 'Fidole', 'Gorton', 'fgorton2k@jiathis.com', 'M', 'MS'),
       (94, 'Teodor', 'Jennions', 'tjennions2l@usda.gov', 'M', 'MS'),
       (95, 'Willi', 'Smolan', 'wsmolan2m@google.cn', 'M', 'MS'),
       (96, 'Jordon', 'Bultitude', 'jbultitude2n@loc.gov', 'F', 'MS'),
       (97, 'Salvidor', 'Abramovitch', 'sabramovitch2o@linkedin.com', 'F', 'GP'),
       (98, 'Merrel', 'Shippey', 'mshippey2p@example.com', 'M', 'GP'),
       (99, 'Hurlee', 'Jepperson', 'hjepperson2q@about.com', 'F', 'GP'),
       (100, 'Ferrell', 'Rosser', 'frosser2r@sfgate.com', 'F', 'GP'),
       (101, 'Martin', 'Foster', 'mfoster@sfgate.com', 'M', 'GP');
